// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoCarnets.Services;

#nullable disable

namespace ProyectoCarnets.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251208211702_notNullable")]
    partial class notNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoCarnets.Models.ActividadComplementaria", b =>
                {
                    b.Property<int>("Clave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Clave"));

                    b.Property<string>("NombreActividad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Clave");

                    b.ToTable("ActividadesComplementarias");
                });

            modelBuilder.Entity("ProyectoCarnets.Models.Alumno", b =>
                {
                    b.Property<int>("Matricula")
                        .HasColumnType("int");

                    b.Property<string>("ApellidoMaterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApellidoPaterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Etapa")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Matricula");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("ProyectoCarnets.Models.AlumnoPrograma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoMatricula")
                        .HasColumnType("int");

                    b.Property<int>("ProgramaEducativoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoMatricula");

                    b.HasIndex("ProgramaEducativoId");

                    b.ToTable("AlumnosProgramas");
                });

            modelBuilder.Entity("ProyectoCarnets.Models.Carnet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActividadComplementariaClave")
                        .HasColumnType("int");

                    b.Property<int>("AlumnoMatricula")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProgramaEducativoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActividadComplementariaClave");

                    b.HasIndex("AlumnoMatricula");

                    b.HasIndex("ProgramaEducativoId");

                    b.ToTable("Carnets");
                });

            modelBuilder.Entity("ProyectoCarnets.Models.ProgramaEducativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Clave")
                        .HasColumnType("int");

                    b.Property<string>("NombrePrograma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProgramasEducativos");
                });

            modelBuilder.Entity("ProyectoCarnets.Models.AlumnoPrograma", b =>
                {
                    b.HasOne("ProyectoCarnets.Models.Alumno", "Alumno")
                        .WithMany("AlumnoProgramas")
                        .HasForeignKey("AlumnoMatricula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoCarnets.Models.ProgramaEducativo", "ProgramaEducativo")
                        .WithMany()
                        .HasForeignKey("ProgramaEducativoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("ProgramaEducativo");
                });

            modelBuilder.Entity("ProyectoCarnets.Models.Carnet", b =>
                {
                    b.HasOne("ProyectoCarnets.Models.ActividadComplementaria", "ActividadComplementaria")
                        .WithMany()
                        .HasForeignKey("ActividadComplementariaClave")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoCarnets.Models.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoMatricula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoCarnets.Models.ProgramaEducativo", "ProgramaEducativo")
                        .WithMany()
                        .HasForeignKey("ProgramaEducativoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActividadComplementaria");

                    b.Navigation("Alumno");

                    b.Navigation("ProgramaEducativo");
                });

            modelBuilder.Entity("ProyectoCarnets.Models.Alumno", b =>
                {
                    b.Navigation("AlumnoProgramas");
                });
#pragma warning restore 612, 618
        }
    }
}
